export const PANEL = {
  surface: 'bg-zinc-800',
  surfaceHover: 'hover:bg-zinc-700',
  surfaceActive: 'bg-zinc-700',
  accent: 'bg-green-500',
  accentHover: 'hover:bg-green-600',
  accentText: 'text-green-500',
  accentBg: 'bg-green-500/10',
  accentBorder: 'border-green-500',
  accentBorderSubtle: 'border-green-500/30',
  label: 'text-zinc-400 text-sm',
  labelFixed: 'text-zinc-400 text-sm w-20 shrink-0',
  sublabel: 'text-zinc-500 text-xs',
  heading: 'text-white text-base font-semibold',
  headingSm: 'text-white text-sm font-semibold',
  value: 'text-white text-sm',
  border: 'border-white/5',
  borderSurface: 'border-zinc-700',
  focusRing: 'focus:outline-none focus:ring-1 focus:ring-green-500',
  toggleOn: 'bg-green-500',
  toggleOff: 'bg-zinc-700',
  input: 'bg-zinc-800 text-white text-sm px-3 py-2 rounded-lg focus:outline-none focus:ring-1 focus:ring-green-500',
  btnPrimary: 'bg-green-500 text-white hover:bg-green-600',
  btnSecondary: 'bg-zinc-800 text-white hover:bg-zinc-700',
  btnDestructive: 'bg-red-600/10 text-red-400 hover:bg-red-600/20',
  btnAccent: 'bg-green-500/10 text-green-500 border border-green-500/30 hover:bg-green-500/20',
  section: 'border-b border-white/5',
} as const
